manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1:
      p: 300.0
      i: 35.0
      d: 1.0
    joint2:
      p: 500.0
      i: 40.0
      d: 1.6
    joint3:
      p: 200.0
      i: 9.0
      d: 6.0
    joint4:
      p: 50.0
      i: 2.0
      d: 0.1
    

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50